Project Authentication
OlukaDenis/members-only pull request #8
Opened 2020-01-29 21:32 UTC by OlukaDenis

- [ ]Sign in and signout
- [ ] Forms
- [ ] Sessions
- [ ] Validations
- [ ] Remember me

2020-01-30 11:17 UTC, maelfosso requested changes
# Changes required

Hello @OlukaDenis 

You did a really nice job. However, there are a some changes that you need to do to move forward.

1. I was not easy to run your code. Read the comment I left below.

2. Please, forgot about using `session`. Only think about `cookies`.
![Screenshot from 2019-12-12 18-19-27](https://user-images.githubusercontent.com/8848104/73442656-845a1a00-4355-11ea-9b80-70b9f26bc7ec.png)
Refer to that screenshot.

Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-01-30 11:17 UTC, maelfosso commented on app/models/user.rb
> +    update_attribute(:remember_digest, User.digest(remember_token))
That line causes me a lot of trouble. I was obliged to comment it to be able to run your project.

2020-01-30 11:17 UTC, maelfosso commented on app/helpers/sessions_helper.rb
> +    session[:user_id] = user.id
Don't use `session`

- Generate and Update the user `remember_token` here
- And then call you `remember(user)` method

2020-01-30 13:35 UTC, OlukaDenis commented on app/helpers/sessions_helper.rb
> +  end
I really don't understand why I am not supposed to use sessions in this case. 
Sessions will be used temporarily when a user doesn't tick the remember me checkbox while logging in.
`current_user` will then pick either `session` or the permanent `cookies`.
Please may you elaborate more to the change

2020-01-30 13:44 UTC, OlukaDenis commented on app/models/user.rb
> +    update_attribute(:remember_digest, User.digest(remember_token))
This works well from my end

2020-01-31 16:59 UTC, Ispirett approved these changes
Status approved :+1: 
Great work @OlukaDenis  :100:  you can move on now!

2020-01-31 17:23 UTC, merged